from django.db import models

class Ocr(models.Model):
    document_type = models.CharField(max_length=300 )
    system_type = models.CharField(max_length=300,null=True)
    system_name = models.CharField(max_length=300,null=True)
    job_card_no = models.CharField(max_length=300,null=True)
    batch_set_id = models.CharField(max_length=300, null=True)
    bhd_no = models.CharField(max_length=300, null=True)
    activity_type = models.CharField(max_length=300, null=True)
    ref_criteria = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=False, null=True)
    status = models.CharField(max_length=300,null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

class assemblies(models.Model):
    id = models.AutoField(primary_key=True)
    system_type = models.CharField(max_length=300)
    system_name = models.CharField(max_length=300)
    assembly_name = models.CharField(max_length=300)
    batch_set_id = models.CharField(max_length=300, null=True)
    bhd_no = models.CharField(max_length=300, null=True)
    activity_type = models.CharField(max_length=300, null=True)
    title = models.CharField(max_length=300, null=True)
    ref_criteria = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=False, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=False, null=True)


class sub_assemblies(models.Model):
    id = models.AutoField(primary_key=True)
    system_type = models.CharField(max_length=300)
    system_name = models.CharField(max_length=300)
    assembly_name = models.CharField(max_length=300)
    sub_assembly_name = models.CharField(max_length=300)
    batch_set_id = models.CharField(max_length=300, null=True)
    bhd_no = models.CharField(max_length=300, null=True)
    activity_type = models.CharField(max_length=300, null=True)
    title = models.CharField(max_length=300, null=True)
    ref_criteria = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=False, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=False, null=True)


class qualification_test(models.Model):
    id = models.AutoField(primary_key=True)
    system_type = models.CharField(max_length=300)
    system_name = models.CharField(max_length=300)
    assembly_name = models.CharField(max_length=300)
    sub_assembly_name = models.CharField(max_length=300)
    qualification_test = models.CharField(max_length=300)
    batch_set_id = models.CharField(max_length=300, null=True)
    bhd_no = models.CharField(max_length=300, null=True)
    activity_type = models.CharField(max_length=300, null=True)
    title = models.CharField(max_length=300, null=True)
    ref_criteria = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=False, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=False, null=True)

class acceptance_test(models.Model):
    id = models.AutoField(primary_key=True)
    system_type = models.CharField(max_length=300)
    system_name = models.CharField(max_length=300)
    assembly_name = models.CharField(max_length=300)
    sub_assembly_name = models.CharField(max_length=300)
    acceptance_test = models.CharField(max_length=300)
    batch_set_id = models.CharField(max_length=300, null=True)
    bhd_no = models.CharField(max_length=300, null=True)
    activity_type = models.CharField(max_length=300, null=True)
    title = models.CharField(max_length=300, null=True)
    ref_criteria = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=False, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=False, null=True)

class sample_qualification_reports(models.Model):
    id = models.AutoField(primary_key=True)
    system_type = models.CharField(max_length=300)
    system_name = models.CharField(max_length=300)
    assembly_name = models.CharField(max_length=300)
    sub_assembly_name = models.CharField(max_length=300)
    sample_qualification_reports = models.CharField(max_length=300)
    batch_set_id = models.CharField(max_length=300, null=True)
    bhd_no = models.CharField(max_length=300, null=True)
    activity_type = models.CharField(max_length=300, null=True)
    title = models.CharField(max_length=300, null=True)
    ref_criteria = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=False, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=False, null=True)

class material_silicon_phenolic(models.Model):
    id = models.AutoField(primary_key=True)
    system_type = models.CharField(max_length=300)
    system_name = models.CharField(max_length=300)
    assembly_name = models.CharField(max_length=300)
    sub_assembly_name = models.CharField(max_length=300)
    material_silicon_phenolic = models.CharField(max_length=300)
    batch_set_id = models.CharField(max_length=300, null=True)
    bhd_no = models.CharField(max_length=300, null=True)
    activity_type = models.CharField(max_length=300, null=True)
    title = models.CharField(max_length=300, null=True)
    ref_criteria = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=False, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=False, null=True)
class batch_bhd_activity(models.Model):
    id = models.AutoField(primary_key=True)
    system_name = models.CharField(max_length=300)
    batch_set_id = models.CharField(max_length=300, null=True)
    bhd_no = models.CharField(max_length=300, null=True)
    activity_type = models.CharField(max_length=300, null=True)
    title = models.CharField(max_length=300, null=True)
    ref_criteria = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=False, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=False, null=True)


class qualification_ocr_report(models.Model):
    id = models.AutoField(primary_key=True)
    system_type = models.CharField(max_length=300)
    system_name = models.CharField(max_length=300)
    assembly_name = models.CharField(max_length=300)
    sub_assembly_name = models.CharField(max_length=300)
    qualification_test = models.CharField(max_length=300)
    acceptance_test = models.CharField(max_length=300, null=True)
    qualification_report = models.CharField(max_length=300, null=True)
    material_silicon_phenolic = models.CharField(max_length=300, null=True)
    batch_set_id = models.CharField(max_length=300, null=True)
    bhd_no = models.CharField(max_length=300, null=True)
    activity_type = models.CharField(max_length=300, null=True)
    title = models.CharField(max_length=300, null=True)
    ref_criteria = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=False, null=True)
    ocr_report = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=False, null=True)


